### PR TITLE
Sidekiq env vars

### PR DESCRIPTION
**Pull request by parubets**
allow to pass ENV variables to sidekiq

### CODE REVIEW

**Comment by seuros** [comment]
:-1: 
You have to use another method, like setting them in .env, .rbenv-var or /etc/environnement ...

How are you going to handle the case when sidekiq crashes and you have to restart it , or the server get rebooted.

**Comment by parubets** [comment]
Hi!, sorry for miss understanding... I'm actually using .env
But, as you know, sensitive information stored in .env files still can be accessible, and values get read.
So, in my case - i needed to pass some ENV variables without storing them on a server, only on my local machine. And yes, if someone crash/restart process - variables will wipe-out, so no one can read them outside of the process :)

For sure, this is some super special case, and i just wanted to propose it here.

Thanks!

**Comment by seuros** [comment]
Sorry, i can't merge this special case, since it will make others believe that it good practice. 
FYI, there is ways to get the ENVs from the running process if the intruder has enough experience/skills.

**Comment by parubets** [comment]
I think it's possible only when intruded has a root access... Do you know how to do this from the user running sidekiq process?

**Pull request closed without merging**
