### PR TITLE
Allow the definition of  service_unit_name

### PR DESCRIPTION
**Pull request by seuros**
fixes 296

@bart3r can you check if this change works for you ?

### CODE REVIEW

**Comment by bart3r** [comment]
@seuros I tried this and it works beautifully!

As you can see it is now calling the service as required:
```
03:30 sidekiq:start
      01 sudo systemctl start sidekiq
    ✔ 01 deploy@web 10.457s
```

Thank you very much for your efforts. When do you think this can be merged into master?

**Comment by seuros** [comment]
I will release it shortly.

**Comment by bart3r** [comment]
Do you bump the gemfile version for these type of changes?

**Comment by seuros** [comment]
yes use 2.2.0 from rubygems

**Pull request merged**
