### PR TITLE
Fix invalid multibyte char error

### LINKED ISSUE #303: invalid multibyte char
Any idea why we one of our users is getting the following error:
```
docker@4891b4ae3388:/rails$ cap deploy production
(Backtrace restricted to imported tasks)
cap aborted!
SyntaxError: /usr/share/rvm/gems/ruby-2.7.2@myapp/gems/capistrano-sidekiq-2.2.0/lib/capistrano/tasks/systemd.rake:53: invalid multibyte char (US-ASCII)
/usr/share/rvm/gems/ruby-2.7.2@myapp/gems/capistrano-sidekiq-2.2.0/lib/capistrano/tasks/systemd.rake:53: invalid multibyte char (US-ASCII)
/usr/share/rvm/gems/ruby-2.7.2@myapp/gems/capistrano-sidekiq-2.2.0/lib/capistrano/tasks/systemd.rake:53: invalid multibyte char (US-ASCII)
/usr/share/rvm/gems/ruby-2.7.2@myapp/gems/capistrano-sidekiq-2.2.0/lib/capistrano/tasks/systemd.rake:55: invalid multibyte char (US-ASCII)
/usr/share/rvm/gems/ruby-2.7.2@myapp/gems/capistrano-sidekiq-2.2.0/lib/capistrano/tasks/systemd.rake:55: invalid multibyte char (US-ASCII)
/usr/share/rvm/gems/ruby-2.7.2@myapp/gems/capistrano-sidekiq-2.2.0/lib/capistrano/tasks/systemd.rake:55: invalid multibyte char (US-ASCII)
/rails/capfile:42:in `<top (required)>'
(See full trace by running task with --trace)
```

As you can see we are using ruby 2.7.2 and the latest version of the capistrano-sidekiq gem

### PR DESCRIPTION
**Pull request by xyassini**
Fixes #303

### CODE REVIEW

**Comment by seuros** [comment]
I can't reproduce this error .

**Comment by dilshod** [comment]
I have the same issue with ruby 2.7.5
```
SyntaxError: /usr/local/rvm/gems/ruby-2.7.5/gems/capistrano-sidekiq-2.3.0/lib/capistrano/tasks/systemd.rake:53: invalid multibyte char (US-ASCII)
```

**Comment by dilshod** [comment]
Same error on ruby 3.0
```
SyntaxError: /usr/local/rvm/gems/ruby-3.0.4/gems/capistrano-sidekiq-2.3.0/lib/capistrano/tasks/systemd.rake:53: invalid multibyte char (US-ASCII)
```

**Comment by seuros** [comment]
@dilshod  , sorry i meant the version of this gem : https://github.com/seuros/capistrano-example-app/blob/rubygems/Gemfile#L25

The new version has better api sync with capistrano3-puma 

The repo i shared is a sample application with different configuration setting.

I'm planning in testing again these gems thoroughly this weekend before final release.

**Comment by WvanLelyveld** [comment]
Can we please merge this? Seems like a no risk fix, and we're experiencing the same problem.
I don't think this should require a major version bump.

**Comment by WvanLelyveld** [comment]
thanks

**Comment by seuros** [comment]
Can you try master branch so i release iy

**Comment by WvanLelyveld** [comment]
> Can you try master branch so i release it.

I tried it again, but it still failed. [The master branch of xyassini](https://github.com/xyassini/capistrano-sidekiq/tree/master) worked without problem though, so I'm investigating what the problem is now, as his fork was like 8 commit behind your master branch.

**Comment by WvanLelyveld** [comment]
Sooo.. Here a my findings:
Since the PR merged into master, it really updates the unreleased changes of your 3.0.0 version in master.
This does not work directly in our use case, as we're stilling using 2.3.0.
The PR should have been branched off from your 2.3.0 tag, so when merged, that could become a 2.3.1 version that would work for us, just like [xyassini's fork](https://github.com/xyassini/capistrano-sidekiq/tree/master).

**Comment by seuros** [comment]
I will do it. 
I will also update the migration to 3.0.0.

**Pull request merged**
