### PR TITLE
Set MALLOC_ARENA_MAX=2

### PR DESCRIPTION
**Pull request by Tensho**
https://www.mikeperham.com/2018/04/25/taming-rails-memory-bloat

### CODE REVIEW

**Comment by seuros** [comment]
Thank for your contribution.
I dont think it should be the responsibility of a deployment tool to decide to optimize the memory.

**Comment by Tensho** [comment]
I see your point, but It's an official suggestion from @mperham...
https://github.com/mperham/sidekiq/blob/master/examples/systemd/sidekiq.service#L38
As far as we move to init system integrations I'd consider keeping best practices is what such tool like `capistrano-sidekiq`. Sidekiq 6 drops demonization in favor of external process supervisors – systemd, upstart.

**Comment by seuros** [comment]
I'm aware it a suggestion, it could be set in README.

That value will override any previous value set via .env or /etc/environment. 

Setting MALLOC_ARENA_MAX will give a better memory usage, but not setting it will give the best performance.
What if someone want performance over memory ?

I'm aware of Sidekiq 6 drop of -d. I will release a new  version of this gem supporting only 6+

**Comment by Tensho** [comment]
I see, fair enough, thank you for your time 🙇

**Pull request closed without merging**
