### PR TITLE
Gem cleanup

### PR DESCRIPTION
**Pull request by kajisaap**
This removes all the monit and monit related references. We don't want Monit as our process supervisor ! period. 
Some consistency for sidekiq process related file handles eg. logfile name, pid file name etc.

### CODE REVIEW

**Comment by kajisaap** [comment]
sorry was supposed to send this in our fork, my bad

**Comment by seuros** [comment]
no problem . I was confused for a while :smiley_cat:

**Comment by seuros** [comment]
Btw you know that monit tasks are optionals, you just have to not require them.

**Comment by kajisaap** [comment]
yes i am aware of it. But I really did not like the naming of pid name when there is one sidekiq process vs when there are multiple sidekiq processes. It might be just me though ;)

**Pull request closed without merging**
