### PR TITLE
[WIP]Allow different queue per role on capistrano3

### PR DESCRIPTION
**Pull request by w1mvy**
#85 is happening conflict.

So, solved conflict, and change logic to check queue per host by [this commit](https://github.com/seuros/capistrano-sidekiq/commit/81a679bb74b4817f4c833bca61b1968ec5b5f87f)

### CODE REVIEW

**Comment by w1mvy** [comment]
@RobinClowers Thanks for your changes, and you can review this PR?

**Comment by RobinClowers** [comment]
Seems fine to me, thanks!

**Comment by vnazarenko** [comment]
Hey, any update?

**Comment by w1mvy** [comment]
Oh, sorry. I will be resolve conflict.

**Comment by w1mvy** [comment]
Fix conflict. but, not check yet.

**Comment by w1mvy** [comment]
#141 #149 
Already exist simple or flexible settings PullRequest. 
So, this pr is close.

**Pull request closed without merging**
